
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T09:49:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc5448730d73311150421a4bec0930315d39cf9b",
 "version": "1.9.149"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
