
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-10T16:58:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4024a233c6475e7e757d82e522dfca11089ada6a",
 "version": "1.9.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
